[package]
name = "wolfram_wxf"
version = "0.2.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/GalAster/wolfram-exchange"
readme = "../../README.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
# ordered-float = "1.0"
num = "0.2"
serde_json = {version="1.0",optional=true}

[features]
default = []
json = ["serde_json"]
